version: '3.1'

services:
  db:
    build: .
    container_name: tcc-project-db
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tcc-project-db